#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: OpenWrt-ConfigFile

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags'
        required: false 
        type: boolean

permissions:
  contents: read

jobs:

  build_openwrt:

#    permissions:
#      contents: write

    name: Build OpenWrt Firmware

    runs-on: ubuntu-latest

    steps:

      - name: Space cleanup and Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          # docker rmi `docker images -q`
          # docker images -q | grep -q . && docker rmi $(docker images -q)
          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt-mark hold grub-efi-amd64-signed
          sudo -E apt update
          # sudo -E apt -y purge azure-cli* docker* ghc* zulu* llvm* firefox google* dotnet* powershell* openjdk* mysql* php* mongodb* dotnet* snap*
          sudo -E apt -y full-upgrade
          # sudo -E apt -y install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5 libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lld llvm lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip python3-ply python-docutils python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          sudo -E bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'
          sudo -E systemctl daemon-reload
          sudo -E apt -y autoremove --purge
          sudo -E apt clean
          sudo -E timedatectl set-timezone "Asia/Shanghai"
      - name: Checkout OpenWrt
        uses: actions/checkout@v4
      - name: Update feeds
        run: |
          # sed -i 's/#src-git helloworld/src-git helloworld/g' ./feeds.conf.default
          # sed -i '$a \src-git OpenClash https://github.com/vernesong/OpenClash' ./feeds.conf.default
          # sed -i '$a \src-git passwall2 https://github.com/xiaorouji/openwrt-passwall2.git;main' ./feeds.conf.default
          # git clone https://github.com/kongfl888/luci-app-adguardhome ./package/luci-app-adguardhome
          # git clone https://github.com/xiaorouji/openwrt-passwall2 ./package/luci-app-passwall2
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Generate configuration file
        run: |
          #rm -f ./.config*
          #touch ./.config
                             
          #cat >> .config <<EOF
          ##
          
          # CONFIG_PACKAGE_luci-app-mosdns=y
          # CONFIG_PACKAGE_luci-app-adguardhome=y
          # CONFIG_PACKAGE_luci-app-passwall2=y
          
          ##
          #EOF
          
          #
          # ===============================================================
          # 
          
          #sed -i 's/^[ \t]*//g' ./.config
          make defconfig
          
      - name: Deliver configtest
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_config
          path: .config
